### ISSUE TITLE
请教一下这个是怎么做到的

### ISSUE THREAD

**Issue by Joyrocky** [cuishuang/explain-source-code-by-chatgpt#1]
请教一下这个是怎么做到的，是直接写Prompt还是把文件喂给ChatGPT呢

**Comment by cuishuang** [comment]
> 请教一下这个是怎么做到的，是直接写Prompt还是把文件喂给ChatGPT呢

openai有开放的接口，但是有频次和额度/费用方面的问题

**Comment by Joyrocky** [comment]
> > 请教一下这个是怎么做到的，是直接写Prompt还是把文件喂给ChatGPT呢
> 
> openai有开放的接口，但是有频次和额度/费用方面的问题

有链接或者地址可以了解一下吗

**Comment by cuishuang** [comment]
> > > 请教一下这个是怎么做到的，是直接写Prompt还是把文件喂给ChatGPT呢
> > 
> > 
> > openai有开放的接口，但是有频次和额度/费用方面的问题
> 
> 有链接或者地址可以了解一下吗

可以看下这个 https://platform.openai.com/account/rate-limits

**Comment by isshe** [comment]
请问这个问题是怎么问的？直接把一个文件内的源码贴给它？让它解释么？但是它好像有字数限制？能否给一个示例？

**Comment by cuishuang** [comment]
> 请问这个问题是怎么问的？直接把一个文件内的源码贴给它？让它解释么？但是它好像有字数限制？能否给一个示例？

就是类似于"请问xx文件的xx方法有什么作用？请详细解释"

**Comment by isshe** [comment]
好的，多谢。不是整个文件问的话，工作量应该也不小。

**Comment by zhqqqy** [comment]
用的3.5吗？3.5不是只有21年之前的数据吗？

**Comment by mmungdong** [comment]
> > 请问这个问题是怎么问的？直接把一个文件内的源码贴给它？让它解释么？但是它好像有字数限制？能否给一个示例？
> 
> 就是类似于"请问xx文件的xx方法有什么作用？请详细解释"

这应该是写了个遍历扔给chatgpt再用相同的文件去接住回复的内容吧？

**Comment by cuishuang** [comment]
> 用的3.5吗？3.5不是只有21年之前的数据吗？

4.0也是2021年9月之前的数据

**Comment by cuishuang** [comment]
> > > 请问这个问题是怎么问的？直接把一个文件内的源码贴给它？让它解释么？但是它好像有字数限制？能否给一个示例？
> > 
> > 
> > 就是类似于"请问xx文件的xx方法有什么作用？请详细解释"
> 
> 这应该是写了个遍历扔给chatgpt再用相同的文件去接住回复的内容吧？

差不多是这样的
