### ISSUE TITLE
能否增加runC项目的源码解释？

### ISSUE THREAD

**Issue by Cyankio** [cuishuang/explain-source-code-by-chatgpt#3]
[https://github.com/opencontainers/runc](https://github.com/opencontainers/runc)

**Comment by cuishuang** [comment]
> 

好的，安排

**Comment by cuishuang** [comment]
> https://github.com/opencontainers/runc

供参考  https://github.com/cuishuang/explain-source-code-by-chatgpt/tree/main/runc/libcontainer

**Comment by Cyankio** [comment]
nice，非常感谢！
