### ISSUE TITLE
看了一下go runtime的proc.go.md，几乎没法用啊，可惜

### ISSUE THREAD

**Issue by hyj443** [cuishuang/explain-source-code-by-chatgpt#5]
我自己也做了一些源码批注，chatgpt解析的错误太多了，而且它说的头头是道的，但放到具体函数里就是不是那么一回事，可惜了，别的仓库也是类似的情况吗？

**Comment by cuishuang** [comment]
差不多，仅供参考吧

**Comment by NietzscheX** [comment]
可以支持c#的项目么？比如https://github.com/Wholesome-wRobot/Wholesome-Auto-Quester这个项目

**Comment by cuishuang** [comment]
不支持

**Comment by cuishuang** [comment]
> 可以支持c#的项目么？比如[https://github.com/Wholesome-wRobot/Wholesome-Auto-Quester这个项目](https://github.com/Wholesome-wRobot/Wholesome-Auto-Quester%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE)

不支持
